### ISSUE TITLE
Add task on hardhat network feature

### ISSUE THREAD

**Issue by Rubilmax** [Rubilmax/hardhat-deal#3]
## Feature Request

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

## Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

From https://github.com/Karuzzzo/deals/blob/master/src/deal.ts

**Comment by Karuzzzo** [comment]
Wow, very cool code! 
I thought about using set_storage, but it felt really hard to implement.

Instead, I implemented less sophisticated approach, call hardhat_impersonateAccount on token contract, and transfer from token address to destination :)

One thing, would be cool to have info about token symbols, to simplify calls from CLI.  
Will change my code accordingly in a day-two, and make a PR.

**Comment by Rubilmax** [comment]
So I merged & deployed the npm package with your changes!
I removed the decimals auto-calculation for now, because it's overly complex for not that much benefit (and would also make the plugin hardly dependent on ethers)
